# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /C/msys64/mingw64/bin/cmake.exe

# The command to remove a file.
RM = /C/msys64/mingw64/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /D/src/reverse_engineering/jopadan/dcc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /D/src/reverse_engineering/jopadan/dcc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/C/msys64/mingw64/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/C/msys64/mingw64/bin/cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/C/msys64/mingw64/bin/cmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/C/msys64/mingw64/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/C/msys64/mingw64/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /D/src/reverse_engineering/jopadan/dcc/CMakeFiles /D/src/reverse_engineering/jopadan/dcc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /D/src/reverse_engineering/jopadan/dcc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dcc_original

# Build rule for target.
dcc_original: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcc_original
.PHONY : dcc_original

# fast build rule for target.
dcc_original/fast:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/build
.PHONY : dcc_original/fast

#=============================================================================
# Target rules for targets named dcc_lib

# Build rule for target.
dcc_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcc_lib
.PHONY : dcc_lib

# fast build rule for target.
dcc_lib/fast:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/build
.PHONY : dcc_lib/fast

#=============================================================================
# Target rules for targets named dcc_original_autogen

# Build rule for target.
dcc_original_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcc_original_autogen
.PHONY : dcc_original_autogen

# fast build rule for target.
dcc_original_autogen/fast:
	$(MAKE) -f CMakeFiles/dcc_original_autogen.dir/build.make CMakeFiles/dcc_original_autogen.dir/build
.PHONY : dcc_original_autogen/fast

#=============================================================================
# Target rules for targets named dcc_lib_autogen

# Build rule for target.
dcc_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcc_lib_autogen
.PHONY : dcc_lib_autogen

# fast build rule for target.
dcc_lib_autogen/fast:
	$(MAKE) -f CMakeFiles/dcc_lib_autogen.dir/build.make CMakeFiles/dcc_lib_autogen.dir/build
.PHONY : dcc_lib_autogen/fast

#=============================================================================
# Target rules for targets named disasm_s

# Build rule for target.
disasm_s: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disasm_s
.PHONY : disasm_s

# fast build rule for target.
disasm_s/fast:
	$(MAKE) -f 3rd_party/libdisasm/CMakeFiles/disasm_s.dir/build.make 3rd_party/libdisasm/CMakeFiles/disasm_s.dir/build
.PHONY : disasm_s/fast

#=============================================================================
# Target rules for targets named disasm

# Build rule for target.
disasm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disasm
.PHONY : disasm

# fast build rule for target.
disasm/fast:
	$(MAKE) -f 3rd_party/libdisasm/CMakeFiles/disasm.dir/build.make 3rd_party/libdisasm/CMakeFiles/disasm.dir/build
.PHONY : disasm/fast

#=============================================================================
# Target rules for targets named disasm_s_autogen

# Build rule for target.
disasm_s_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disasm_s_autogen
.PHONY : disasm_s_autogen

# fast build rule for target.
disasm_s_autogen/fast:
	$(MAKE) -f 3rd_party/libdisasm/CMakeFiles/disasm_s_autogen.dir/build.make 3rd_party/libdisasm/CMakeFiles/disasm_s_autogen.dir/build
.PHONY : disasm_s_autogen/fast

#=============================================================================
# Target rules for targets named disasm_autogen

# Build rule for target.
disasm_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disasm_autogen
.PHONY : disasm_autogen

# fast build rule for target.
disasm_autogen/fast:
	$(MAKE) -f 3rd_party/libdisasm/CMakeFiles/disasm_autogen.dir/build.make 3rd_party/libdisasm/CMakeFiles/disasm_autogen.dir/build
.PHONY : disasm_autogen/fast

#=============================================================================
# Target rules for targets named dcc_hash

# Build rule for target.
dcc_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcc_hash
.PHONY : dcc_hash

# fast build rule for target.
dcc_hash/fast:
	$(MAKE) -f common/CMakeFiles/dcc_hash.dir/build.make common/CMakeFiles/dcc_hash.dir/build
.PHONY : dcc_hash/fast

#=============================================================================
# Target rules for targets named dcc_hash_autogen

# Build rule for target.
dcc_hash_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dcc_hash_autogen
.PHONY : dcc_hash_autogen

# fast build rule for target.
dcc_hash_autogen/fast:
	$(MAKE) -f common/CMakeFiles/dcc_hash_autogen.dir/build.make common/CMakeFiles/dcc_hash_autogen.dir/build
.PHONY : dcc_hash_autogen/fast

#=============================================================================
# Target rules for targets named dispsig

# Build rule for target.
dispsig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dispsig
.PHONY : dispsig

# fast build rule for target.
dispsig/fast:
	$(MAKE) -f tools/dispsrch/CMakeFiles/dispsig.dir/build.make tools/dispsrch/CMakeFiles/dispsig.dir/build
.PHONY : dispsig/fast

#=============================================================================
# Target rules for targets named srchsig

# Build rule for target.
srchsig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srchsig
.PHONY : srchsig

# fast build rule for target.
srchsig/fast:
	$(MAKE) -f tools/dispsrch/CMakeFiles/srchsig.dir/build.make tools/dispsrch/CMakeFiles/srchsig.dir/build
.PHONY : srchsig/fast

#=============================================================================
# Target rules for targets named dispsig_autogen

# Build rule for target.
dispsig_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dispsig_autogen
.PHONY : dispsig_autogen

# fast build rule for target.
dispsig_autogen/fast:
	$(MAKE) -f tools/dispsrch/CMakeFiles/dispsig_autogen.dir/build.make tools/dispsrch/CMakeFiles/dispsig_autogen.dir/build
.PHONY : dispsig_autogen/fast

#=============================================================================
# Target rules for targets named srchsig_autogen

# Build rule for target.
srchsig_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 srchsig_autogen
.PHONY : srchsig_autogen

# fast build rule for target.
srchsig_autogen/fast:
	$(MAKE) -f tools/dispsrch/CMakeFiles/srchsig_autogen.dir/build.make tools/dispsrch/CMakeFiles/srchsig_autogen.dir/build
.PHONY : srchsig_autogen/fast

#=============================================================================
# Target rules for targets named makedsig

# Build rule for target.
makedsig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 makedsig
.PHONY : makedsig

# fast build rule for target.
makedsig/fast:
	$(MAKE) -f tools/makedsig/CMakeFiles/makedsig.dir/build.make tools/makedsig/CMakeFiles/makedsig.dir/build
.PHONY : makedsig/fast

#=============================================================================
# Target rules for targets named makedsig_autogen

# Build rule for target.
makedsig_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 makedsig_autogen
.PHONY : makedsig_autogen

# fast build rule for target.
makedsig_autogen/fast:
	$(MAKE) -f tools/makedsig/CMakeFiles/makedsig_autogen.dir/build.make tools/makedsig/CMakeFiles/makedsig_autogen.dir/build
.PHONY : makedsig_autogen/fast

#=============================================================================
# Target rules for targets named readsig

# Build rule for target.
readsig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readsig
.PHONY : readsig

# fast build rule for target.
readsig/fast:
	$(MAKE) -f tools/readsig/CMakeFiles/readsig.dir/build.make tools/readsig/CMakeFiles/readsig.dir/build
.PHONY : readsig/fast

#=============================================================================
# Target rules for targets named readsig_autogen

# Build rule for target.
readsig_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 readsig_autogen
.PHONY : readsig_autogen

# fast build rule for target.
readsig_autogen/fast:
	$(MAKE) -f tools/readsig/CMakeFiles/readsig_autogen.dir/build.make tools/readsig/CMakeFiles/readsig_autogen.dir/build
.PHONY : readsig_autogen/fast

#=============================================================================
# Target rules for targets named parselib

# Build rule for target.
parselib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parselib
.PHONY : parselib

# fast build rule for target.
parselib/fast:
	$(MAKE) -f tools/parsehdr/CMakeFiles/parselib.dir/build.make tools/parsehdr/CMakeFiles/parselib.dir/build
.PHONY : parselib/fast

#=============================================================================
# Target rules for targets named parselib_autogen

# Build rule for target.
parselib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parselib_autogen
.PHONY : parselib_autogen

# fast build rule for target.
parselib_autogen/fast:
	$(MAKE) -f tools/parsehdr/CMakeFiles/parselib_autogen.dir/build.make tools/parsehdr/CMakeFiles/parselib_autogen.dir/build
.PHONY : parselib_autogen/fast

dcc_lib_autogen/mocs_compilation.obj: dcc_lib_autogen/mocs_compilation.cpp.obj

.PHONY : dcc_lib_autogen/mocs_compilation.obj

# target to build an object file
dcc_lib_autogen/mocs_compilation.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/dcc_lib_autogen/mocs_compilation.cpp.obj
.PHONY : dcc_lib_autogen/mocs_compilation.cpp.obj

dcc_lib_autogen/mocs_compilation.i: dcc_lib_autogen/mocs_compilation.cpp.i

.PHONY : dcc_lib_autogen/mocs_compilation.i

# target to preprocess a source file
dcc_lib_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/dcc_lib_autogen/mocs_compilation.cpp.i
.PHONY : dcc_lib_autogen/mocs_compilation.cpp.i

dcc_lib_autogen/mocs_compilation.s: dcc_lib_autogen/mocs_compilation.cpp.s

.PHONY : dcc_lib_autogen/mocs_compilation.s

# target to generate assembly for a file
dcc_lib_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/dcc_lib_autogen/mocs_compilation.cpp.s
.PHONY : dcc_lib_autogen/mocs_compilation.cpp.s

dcc_original_autogen/mocs_compilation.obj: dcc_original_autogen/mocs_compilation.cpp.obj

.PHONY : dcc_original_autogen/mocs_compilation.obj

# target to build an object file
dcc_original_autogen/mocs_compilation.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/dcc_original_autogen/mocs_compilation.cpp.obj
.PHONY : dcc_original_autogen/mocs_compilation.cpp.obj

dcc_original_autogen/mocs_compilation.i: dcc_original_autogen/mocs_compilation.cpp.i

.PHONY : dcc_original_autogen/mocs_compilation.i

# target to preprocess a source file
dcc_original_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/dcc_original_autogen/mocs_compilation.cpp.i
.PHONY : dcc_original_autogen/mocs_compilation.cpp.i

dcc_original_autogen/mocs_compilation.s: dcc_original_autogen/mocs_compilation.cpp.s

.PHONY : dcc_original_autogen/mocs_compilation.s

# target to generate assembly for a file
dcc_original_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/dcc_original_autogen/mocs_compilation.cpp.s
.PHONY : dcc_original_autogen/mocs_compilation.cpp.s

src/BasicBlock.obj: src/BasicBlock.cpp.obj

.PHONY : src/BasicBlock.obj

# target to build an object file
src/BasicBlock.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/BasicBlock.cpp.obj
.PHONY : src/BasicBlock.cpp.obj

src/BasicBlock.i: src/BasicBlock.cpp.i

.PHONY : src/BasicBlock.i

# target to preprocess a source file
src/BasicBlock.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/BasicBlock.cpp.i
.PHONY : src/BasicBlock.cpp.i

src/BasicBlock.s: src/BasicBlock.cpp.s

.PHONY : src/BasicBlock.s

# target to generate assembly for a file
src/BasicBlock.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/BasicBlock.cpp.s
.PHONY : src/BasicBlock.cpp.s

src/CallConvention.obj: src/CallConvention.cpp.obj

.PHONY : src/CallConvention.obj

# target to build an object file
src/CallConvention.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/CallConvention.cpp.obj
.PHONY : src/CallConvention.cpp.obj

src/CallConvention.i: src/CallConvention.cpp.i

.PHONY : src/CallConvention.i

# target to preprocess a source file
src/CallConvention.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/CallConvention.cpp.i
.PHONY : src/CallConvention.cpp.i

src/CallConvention.s: src/CallConvention.cpp.s

.PHONY : src/CallConvention.s

# target to generate assembly for a file
src/CallConvention.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/CallConvention.cpp.s
.PHONY : src/CallConvention.cpp.s

src/DccFrontend.obj: src/DccFrontend.cpp.obj

.PHONY : src/DccFrontend.obj

# target to build an object file
src/DccFrontend.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/DccFrontend.cpp.obj
.PHONY : src/DccFrontend.cpp.obj

src/DccFrontend.i: src/DccFrontend.cpp.i

.PHONY : src/DccFrontend.i

# target to preprocess a source file
src/DccFrontend.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/DccFrontend.cpp.i
.PHONY : src/DccFrontend.cpp.i

src/DccFrontend.s: src/DccFrontend.cpp.s

.PHONY : src/DccFrontend.s

# target to generate assembly for a file
src/DccFrontend.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/DccFrontend.cpp.s
.PHONY : src/DccFrontend.cpp.s

src/Procedure.obj: src/Procedure.cpp.obj

.PHONY : src/Procedure.obj

# target to build an object file
src/Procedure.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/Procedure.cpp.obj
.PHONY : src/Procedure.cpp.obj

src/Procedure.i: src/Procedure.cpp.i

.PHONY : src/Procedure.i

# target to preprocess a source file
src/Procedure.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/Procedure.cpp.i
.PHONY : src/Procedure.cpp.i

src/Procedure.s: src/Procedure.cpp.s

.PHONY : src/Procedure.s

# target to generate assembly for a file
src/Procedure.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/Procedure.cpp.s
.PHONY : src/Procedure.cpp.s

src/RegisterNode.obj: src/RegisterNode.cpp.obj

.PHONY : src/RegisterNode.obj

# target to build an object file
src/RegisterNode.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/RegisterNode.cpp.obj
.PHONY : src/RegisterNode.cpp.obj

src/RegisterNode.i: src/RegisterNode.cpp.i

.PHONY : src/RegisterNode.i

# target to preprocess a source file
src/RegisterNode.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/RegisterNode.cpp.i
.PHONY : src/RegisterNode.cpp.i

src/RegisterNode.s: src/RegisterNode.cpp.s

.PHONY : src/RegisterNode.s

# target to generate assembly for a file
src/RegisterNode.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/RegisterNode.cpp.s
.PHONY : src/RegisterNode.cpp.s

src/ast.obj: src/ast.cpp.obj

.PHONY : src/ast.obj

# target to build an object file
src/ast.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/ast.cpp.obj
.PHONY : src/ast.cpp.obj

src/ast.i: src/ast.cpp.i

.PHONY : src/ast.i

# target to preprocess a source file
src/ast.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/ast.cpp.i
.PHONY : src/ast.cpp.i

src/ast.s: src/ast.cpp.s

.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/ast.cpp.s
.PHONY : src/ast.cpp.s

src/backend.obj: src/backend.cpp.obj

.PHONY : src/backend.obj

# target to build an object file
src/backend.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/backend.cpp.obj
.PHONY : src/backend.cpp.obj

src/backend.i: src/backend.cpp.i

.PHONY : src/backend.i

# target to preprocess a source file
src/backend.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/backend.cpp.i
.PHONY : src/backend.cpp.i

src/backend.s: src/backend.cpp.s

.PHONY : src/backend.s

# target to generate assembly for a file
src/backend.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/backend.cpp.s
.PHONY : src/backend.cpp.s

src/bundle.obj: src/bundle.cpp.obj

.PHONY : src/bundle.obj

# target to build an object file
src/bundle.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/bundle.cpp.obj
.PHONY : src/bundle.cpp.obj

src/bundle.i: src/bundle.cpp.i

.PHONY : src/bundle.i

# target to preprocess a source file
src/bundle.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/bundle.cpp.i
.PHONY : src/bundle.cpp.i

src/bundle.s: src/bundle.cpp.s

.PHONY : src/bundle.s

# target to generate assembly for a file
src/bundle.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/bundle.cpp.s
.PHONY : src/bundle.cpp.s

src/chklib.obj: src/chklib.cpp.obj

.PHONY : src/chklib.obj

# target to build an object file
src/chklib.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/chklib.cpp.obj
.PHONY : src/chklib.cpp.obj

src/chklib.i: src/chklib.cpp.i

.PHONY : src/chklib.i

# target to preprocess a source file
src/chklib.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/chklib.cpp.i
.PHONY : src/chklib.cpp.i

src/chklib.s: src/chklib.cpp.s

.PHONY : src/chklib.s

# target to generate assembly for a file
src/chklib.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/chklib.cpp.s
.PHONY : src/chklib.cpp.s

src/comwrite.obj: src/comwrite.cpp.obj

.PHONY : src/comwrite.obj

# target to build an object file
src/comwrite.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/comwrite.cpp.obj
.PHONY : src/comwrite.cpp.obj

src/comwrite.i: src/comwrite.cpp.i

.PHONY : src/comwrite.i

# target to preprocess a source file
src/comwrite.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/comwrite.cpp.i
.PHONY : src/comwrite.cpp.i

src/comwrite.s: src/comwrite.cpp.s

.PHONY : src/comwrite.s

# target to generate assembly for a file
src/comwrite.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/comwrite.cpp.s
.PHONY : src/comwrite.cpp.s

src/control.obj: src/control.cpp.obj

.PHONY : src/control.obj

# target to build an object file
src/control.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/control.cpp.obj
.PHONY : src/control.cpp.obj

src/control.i: src/control.cpp.i

.PHONY : src/control.i

# target to preprocess a source file
src/control.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/control.cpp.i
.PHONY : src/control.cpp.i

src/control.s: src/control.cpp.s

.PHONY : src/control.s

# target to generate assembly for a file
src/control.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/control.cpp.s
.PHONY : src/control.cpp.s

src/dataflow.obj: src/dataflow.cpp.obj

.PHONY : src/dataflow.obj

# target to build an object file
src/dataflow.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/dataflow.cpp.obj
.PHONY : src/dataflow.cpp.obj

src/dataflow.i: src/dataflow.cpp.i

.PHONY : src/dataflow.i

# target to preprocess a source file
src/dataflow.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/dataflow.cpp.i
.PHONY : src/dataflow.cpp.i

src/dataflow.s: src/dataflow.cpp.s

.PHONY : src/dataflow.s

# target to generate assembly for a file
src/dataflow.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/dataflow.cpp.s
.PHONY : src/dataflow.cpp.s

src/dcc.obj: src/dcc.cpp.obj

.PHONY : src/dcc.obj

# target to build an object file
src/dcc.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/src/dcc.cpp.obj
.PHONY : src/dcc.cpp.obj

src/dcc.i: src/dcc.cpp.i

.PHONY : src/dcc.i

# target to preprocess a source file
src/dcc.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/src/dcc.cpp.i
.PHONY : src/dcc.cpp.i

src/dcc.s: src/dcc.cpp.s

.PHONY : src/dcc.s

# target to generate assembly for a file
src/dcc.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_original.dir/build.make CMakeFiles/dcc_original.dir/src/dcc.cpp.s
.PHONY : src/dcc.cpp.s

src/dcc_interface.obj: src/dcc_interface.cpp.obj

.PHONY : src/dcc_interface.obj

# target to build an object file
src/dcc_interface.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/dcc_interface.cpp.obj
.PHONY : src/dcc_interface.cpp.obj

src/dcc_interface.i: src/dcc_interface.cpp.i

.PHONY : src/dcc_interface.i

# target to preprocess a source file
src/dcc_interface.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/dcc_interface.cpp.i
.PHONY : src/dcc_interface.cpp.i

src/dcc_interface.s: src/dcc_interface.cpp.s

.PHONY : src/dcc_interface.s

# target to generate assembly for a file
src/dcc_interface.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/dcc_interface.cpp.s
.PHONY : src/dcc_interface.cpp.s

src/disassem.obj: src/disassem.cpp.obj

.PHONY : src/disassem.obj

# target to build an object file
src/disassem.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/disassem.cpp.obj
.PHONY : src/disassem.cpp.obj

src/disassem.i: src/disassem.cpp.i

.PHONY : src/disassem.i

# target to preprocess a source file
src/disassem.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/disassem.cpp.i
.PHONY : src/disassem.cpp.i

src/disassem.s: src/disassem.cpp.s

.PHONY : src/disassem.s

# target to generate assembly for a file
src/disassem.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/disassem.cpp.s
.PHONY : src/disassem.cpp.s

src/error.obj: src/error.cpp.obj

.PHONY : src/error.obj

# target to build an object file
src/error.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/error.cpp.obj
.PHONY : src/error.cpp.obj

src/error.i: src/error.cpp.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/fixwild.obj: src/fixwild.cpp.obj

.PHONY : src/fixwild.obj

# target to build an object file
src/fixwild.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/fixwild.cpp.obj
.PHONY : src/fixwild.cpp.obj

src/fixwild.i: src/fixwild.cpp.i

.PHONY : src/fixwild.i

# target to preprocess a source file
src/fixwild.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/fixwild.cpp.i
.PHONY : src/fixwild.cpp.i

src/fixwild.s: src/fixwild.cpp.s

.PHONY : src/fixwild.s

# target to generate assembly for a file
src/fixwild.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/fixwild.cpp.s
.PHONY : src/fixwild.cpp.s

src/graph.obj: src/graph.cpp.obj

.PHONY : src/graph.obj

# target to build an object file
src/graph.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/graph.cpp.obj
.PHONY : src/graph.cpp.obj

src/graph.i: src/graph.cpp.i

.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/graph.cpp.i
.PHONY : src/graph.cpp.i

src/graph.s: src/graph.cpp.s

.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/graph.cpp.s
.PHONY : src/graph.cpp.s

src/hlicode.obj: src/hlicode.cpp.obj

.PHONY : src/hlicode.obj

# target to build an object file
src/hlicode.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/hlicode.cpp.obj
.PHONY : src/hlicode.cpp.obj

src/hlicode.i: src/hlicode.cpp.i

.PHONY : src/hlicode.i

# target to preprocess a source file
src/hlicode.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/hlicode.cpp.i
.PHONY : src/hlicode.cpp.i

src/hlicode.s: src/hlicode.cpp.s

.PHONY : src/hlicode.s

# target to generate assembly for a file
src/hlicode.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/hlicode.cpp.s
.PHONY : src/hlicode.cpp.s

src/hltype.obj: src/hltype.cpp.obj

.PHONY : src/hltype.obj

# target to build an object file
src/hltype.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/hltype.cpp.obj
.PHONY : src/hltype.cpp.obj

src/hltype.i: src/hltype.cpp.i

.PHONY : src/hltype.i

# target to preprocess a source file
src/hltype.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/hltype.cpp.i
.PHONY : src/hltype.cpp.i

src/hltype.s: src/hltype.cpp.s

.PHONY : src/hltype.s

# target to generate assembly for a file
src/hltype.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/hltype.cpp.s
.PHONY : src/hltype.cpp.s

src/icode.obj: src/icode.cpp.obj

.PHONY : src/icode.obj

# target to build an object file
src/icode.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/icode.cpp.obj
.PHONY : src/icode.cpp.obj

src/icode.i: src/icode.cpp.i

.PHONY : src/icode.i

# target to preprocess a source file
src/icode.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/icode.cpp.i
.PHONY : src/icode.cpp.i

src/icode.s: src/icode.cpp.s

.PHONY : src/icode.s

# target to generate assembly for a file
src/icode.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/icode.cpp.s
.PHONY : src/icode.cpp.s

src/idioms.obj: src/idioms.cpp.obj

.PHONY : src/idioms.obj

# target to build an object file
src/idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms.cpp.obj
.PHONY : src/idioms.cpp.obj

src/idioms.i: src/idioms.cpp.i

.PHONY : src/idioms.i

# target to preprocess a source file
src/idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms.cpp.i
.PHONY : src/idioms.cpp.i

src/idioms.s: src/idioms.cpp.s

.PHONY : src/idioms.s

# target to generate assembly for a file
src/idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms.cpp.s
.PHONY : src/idioms.cpp.s

src/idioms/arith_idioms.obj: src/idioms/arith_idioms.cpp.obj

.PHONY : src/idioms/arith_idioms.obj

# target to build an object file
src/idioms/arith_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/arith_idioms.cpp.obj
.PHONY : src/idioms/arith_idioms.cpp.obj

src/idioms/arith_idioms.i: src/idioms/arith_idioms.cpp.i

.PHONY : src/idioms/arith_idioms.i

# target to preprocess a source file
src/idioms/arith_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/arith_idioms.cpp.i
.PHONY : src/idioms/arith_idioms.cpp.i

src/idioms/arith_idioms.s: src/idioms/arith_idioms.cpp.s

.PHONY : src/idioms/arith_idioms.s

# target to generate assembly for a file
src/idioms/arith_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/arith_idioms.cpp.s
.PHONY : src/idioms/arith_idioms.cpp.s

src/idioms/call_idioms.obj: src/idioms/call_idioms.cpp.obj

.PHONY : src/idioms/call_idioms.obj

# target to build an object file
src/idioms/call_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/call_idioms.cpp.obj
.PHONY : src/idioms/call_idioms.cpp.obj

src/idioms/call_idioms.i: src/idioms/call_idioms.cpp.i

.PHONY : src/idioms/call_idioms.i

# target to preprocess a source file
src/idioms/call_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/call_idioms.cpp.i
.PHONY : src/idioms/call_idioms.cpp.i

src/idioms/call_idioms.s: src/idioms/call_idioms.cpp.s

.PHONY : src/idioms/call_idioms.s

# target to generate assembly for a file
src/idioms/call_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/call_idioms.cpp.s
.PHONY : src/idioms/call_idioms.cpp.s

src/idioms/epilogue_idioms.obj: src/idioms/epilogue_idioms.cpp.obj

.PHONY : src/idioms/epilogue_idioms.obj

# target to build an object file
src/idioms/epilogue_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/epilogue_idioms.cpp.obj
.PHONY : src/idioms/epilogue_idioms.cpp.obj

src/idioms/epilogue_idioms.i: src/idioms/epilogue_idioms.cpp.i

.PHONY : src/idioms/epilogue_idioms.i

# target to preprocess a source file
src/idioms/epilogue_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/epilogue_idioms.cpp.i
.PHONY : src/idioms/epilogue_idioms.cpp.i

src/idioms/epilogue_idioms.s: src/idioms/epilogue_idioms.cpp.s

.PHONY : src/idioms/epilogue_idioms.s

# target to generate assembly for a file
src/idioms/epilogue_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/epilogue_idioms.cpp.s
.PHONY : src/idioms/epilogue_idioms.cpp.s

src/idioms/idiom1.obj: src/idioms/idiom1.cpp.obj

.PHONY : src/idioms/idiom1.obj

# target to build an object file
src/idioms/idiom1.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/idiom1.cpp.obj
.PHONY : src/idioms/idiom1.cpp.obj

src/idioms/idiom1.i: src/idioms/idiom1.cpp.i

.PHONY : src/idioms/idiom1.i

# target to preprocess a source file
src/idioms/idiom1.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/idiom1.cpp.i
.PHONY : src/idioms/idiom1.cpp.i

src/idioms/idiom1.s: src/idioms/idiom1.cpp.s

.PHONY : src/idioms/idiom1.s

# target to generate assembly for a file
src/idioms/idiom1.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/idiom1.cpp.s
.PHONY : src/idioms/idiom1.cpp.s

src/idioms/mov_idioms.obj: src/idioms/mov_idioms.cpp.obj

.PHONY : src/idioms/mov_idioms.obj

# target to build an object file
src/idioms/mov_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/mov_idioms.cpp.obj
.PHONY : src/idioms/mov_idioms.cpp.obj

src/idioms/mov_idioms.i: src/idioms/mov_idioms.cpp.i

.PHONY : src/idioms/mov_idioms.i

# target to preprocess a source file
src/idioms/mov_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/mov_idioms.cpp.i
.PHONY : src/idioms/mov_idioms.cpp.i

src/idioms/mov_idioms.s: src/idioms/mov_idioms.cpp.s

.PHONY : src/idioms/mov_idioms.s

# target to generate assembly for a file
src/idioms/mov_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/mov_idioms.cpp.s
.PHONY : src/idioms/mov_idioms.cpp.s

src/idioms/neg_idioms.obj: src/idioms/neg_idioms.cpp.obj

.PHONY : src/idioms/neg_idioms.obj

# target to build an object file
src/idioms/neg_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/neg_idioms.cpp.obj
.PHONY : src/idioms/neg_idioms.cpp.obj

src/idioms/neg_idioms.i: src/idioms/neg_idioms.cpp.i

.PHONY : src/idioms/neg_idioms.i

# target to preprocess a source file
src/idioms/neg_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/neg_idioms.cpp.i
.PHONY : src/idioms/neg_idioms.cpp.i

src/idioms/neg_idioms.s: src/idioms/neg_idioms.cpp.s

.PHONY : src/idioms/neg_idioms.s

# target to generate assembly for a file
src/idioms/neg_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/neg_idioms.cpp.s
.PHONY : src/idioms/neg_idioms.cpp.s

src/idioms/shift_idioms.obj: src/idioms/shift_idioms.cpp.obj

.PHONY : src/idioms/shift_idioms.obj

# target to build an object file
src/idioms/shift_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/shift_idioms.cpp.obj
.PHONY : src/idioms/shift_idioms.cpp.obj

src/idioms/shift_idioms.i: src/idioms/shift_idioms.cpp.i

.PHONY : src/idioms/shift_idioms.i

# target to preprocess a source file
src/idioms/shift_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/shift_idioms.cpp.i
.PHONY : src/idioms/shift_idioms.cpp.i

src/idioms/shift_idioms.s: src/idioms/shift_idioms.cpp.s

.PHONY : src/idioms/shift_idioms.s

# target to generate assembly for a file
src/idioms/shift_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/shift_idioms.cpp.s
.PHONY : src/idioms/shift_idioms.cpp.s

src/idioms/xor_idioms.obj: src/idioms/xor_idioms.cpp.obj

.PHONY : src/idioms/xor_idioms.obj

# target to build an object file
src/idioms/xor_idioms.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/xor_idioms.cpp.obj
.PHONY : src/idioms/xor_idioms.cpp.obj

src/idioms/xor_idioms.i: src/idioms/xor_idioms.cpp.i

.PHONY : src/idioms/xor_idioms.i

# target to preprocess a source file
src/idioms/xor_idioms.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/xor_idioms.cpp.i
.PHONY : src/idioms/xor_idioms.cpp.i

src/idioms/xor_idioms.s: src/idioms/xor_idioms.cpp.s

.PHONY : src/idioms/xor_idioms.s

# target to generate assembly for a file
src/idioms/xor_idioms.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/idioms/xor_idioms.cpp.s
.PHONY : src/idioms/xor_idioms.cpp.s

src/liveness_set.obj: src/liveness_set.cpp.obj

.PHONY : src/liveness_set.obj

# target to build an object file
src/liveness_set.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/liveness_set.cpp.obj
.PHONY : src/liveness_set.cpp.obj

src/liveness_set.i: src/liveness_set.cpp.i

.PHONY : src/liveness_set.i

# target to preprocess a source file
src/liveness_set.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/liveness_set.cpp.i
.PHONY : src/liveness_set.cpp.i

src/liveness_set.s: src/liveness_set.cpp.s

.PHONY : src/liveness_set.s

# target to generate assembly for a file
src/liveness_set.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/liveness_set.cpp.s
.PHONY : src/liveness_set.cpp.s

src/locident.obj: src/locident.cpp.obj

.PHONY : src/locident.obj

# target to build an object file
src/locident.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/locident.cpp.obj
.PHONY : src/locident.cpp.obj

src/locident.i: src/locident.cpp.i

.PHONY : src/locident.i

# target to preprocess a source file
src/locident.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/locident.cpp.i
.PHONY : src/locident.cpp.i

src/locident.s: src/locident.cpp.s

.PHONY : src/locident.s

# target to generate assembly for a file
src/locident.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/locident.cpp.s
.PHONY : src/locident.cpp.s

src/machine_x86.obj: src/machine_x86.cpp.obj

.PHONY : src/machine_x86.obj

# target to build an object file
src/machine_x86.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/machine_x86.cpp.obj
.PHONY : src/machine_x86.cpp.obj

src/machine_x86.i: src/machine_x86.cpp.i

.PHONY : src/machine_x86.i

# target to preprocess a source file
src/machine_x86.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/machine_x86.cpp.i
.PHONY : src/machine_x86.cpp.i

src/machine_x86.s: src/machine_x86.cpp.s

.PHONY : src/machine_x86.s

# target to generate assembly for a file
src/machine_x86.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/machine_x86.cpp.s
.PHONY : src/machine_x86.cpp.s

src/parser.obj: src/parser.cpp.obj

.PHONY : src/parser.obj

# target to build an object file
src/parser.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/parser.cpp.obj
.PHONY : src/parser.cpp.obj

src/parser.i: src/parser.cpp.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/procs.obj: src/procs.cpp.obj

.PHONY : src/procs.obj

# target to build an object file
src/procs.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/procs.cpp.obj
.PHONY : src/procs.cpp.obj

src/procs.i: src/procs.cpp.i

.PHONY : src/procs.i

# target to preprocess a source file
src/procs.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/procs.cpp.i
.PHONY : src/procs.cpp.i

src/procs.s: src/procs.cpp.s

.PHONY : src/procs.s

# target to generate assembly for a file
src/procs.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/procs.cpp.s
.PHONY : src/procs.cpp.s

src/project.obj: src/project.cpp.obj

.PHONY : src/project.obj

# target to build an object file
src/project.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/project.cpp.obj
.PHONY : src/project.cpp.obj

src/project.i: src/project.cpp.i

.PHONY : src/project.i

# target to preprocess a source file
src/project.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/project.cpp.i
.PHONY : src/project.cpp.i

src/project.s: src/project.cpp.s

.PHONY : src/project.s

# target to generate assembly for a file
src/project.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/project.cpp.s
.PHONY : src/project.cpp.s

src/proplong.obj: src/proplong.cpp.obj

.PHONY : src/proplong.obj

# target to build an object file
src/proplong.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/proplong.cpp.obj
.PHONY : src/proplong.cpp.obj

src/proplong.i: src/proplong.cpp.i

.PHONY : src/proplong.i

# target to preprocess a source file
src/proplong.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/proplong.cpp.i
.PHONY : src/proplong.cpp.i

src/proplong.s: src/proplong.cpp.s

.PHONY : src/proplong.s

# target to generate assembly for a file
src/proplong.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/proplong.cpp.s
.PHONY : src/proplong.cpp.s

src/reducible.obj: src/reducible.cpp.obj

.PHONY : src/reducible.obj

# target to build an object file
src/reducible.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/reducible.cpp.obj
.PHONY : src/reducible.cpp.obj

src/reducible.i: src/reducible.cpp.i

.PHONY : src/reducible.i

# target to preprocess a source file
src/reducible.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/reducible.cpp.i
.PHONY : src/reducible.cpp.i

src/reducible.s: src/reducible.cpp.s

.PHONY : src/reducible.s

# target to generate assembly for a file
src/reducible.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/reducible.cpp.s
.PHONY : src/reducible.cpp.s

src/scanner.obj: src/scanner.cpp.obj

.PHONY : src/scanner.obj

# target to build an object file
src/scanner.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/scanner.cpp.obj
.PHONY : src/scanner.cpp.obj

src/scanner.i: src/scanner.cpp.i

.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/scanner.cpp.i
.PHONY : src/scanner.cpp.i

src/scanner.s: src/scanner.cpp.s

.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/scanner.cpp.s
.PHONY : src/scanner.cpp.s

src/symtab.obj: src/symtab.cpp.obj

.PHONY : src/symtab.obj

# target to build an object file
src/symtab.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/symtab.cpp.obj
.PHONY : src/symtab.cpp.obj

src/symtab.i: src/symtab.cpp.i

.PHONY : src/symtab.i

# target to preprocess a source file
src/symtab.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/symtab.cpp.i
.PHONY : src/symtab.cpp.i

src/symtab.s: src/symtab.cpp.s

.PHONY : src/symtab.s

# target to generate assembly for a file
src/symtab.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/symtab.cpp.s
.PHONY : src/symtab.cpp.s

src/udm.obj: src/udm.cpp.obj

.PHONY : src/udm.obj

# target to build an object file
src/udm.cpp.obj:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/udm.cpp.obj
.PHONY : src/udm.cpp.obj

src/udm.i: src/udm.cpp.i

.PHONY : src/udm.i

# target to preprocess a source file
src/udm.cpp.i:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/udm.cpp.i
.PHONY : src/udm.cpp.i

src/udm.s: src/udm.cpp.s

.PHONY : src/udm.s

# target to generate assembly for a file
src/udm.cpp.s:
	$(MAKE) -f CMakeFiles/dcc_lib.dir/build.make CMakeFiles/dcc_lib.dir/src/udm.cpp.s
.PHONY : src/udm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... dcc_original"
	@echo "... dcc_lib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... dcc_original_autogen"
	@echo "... dcc_lib_autogen"
	@echo "... disasm_s"
	@echo "... disasm"
	@echo "... disasm_s_autogen"
	@echo "... disasm_autogen"
	@echo "... dcc_hash"
	@echo "... dcc_hash_autogen"
	@echo "... dispsig"
	@echo "... srchsig"
	@echo "... dispsig_autogen"
	@echo "... srchsig_autogen"
	@echo "... makedsig"
	@echo "... makedsig_autogen"
	@echo "... readsig"
	@echo "... readsig_autogen"
	@echo "... parselib"
	@echo "... parselib_autogen"
	@echo "... dcc_lib_autogen/mocs_compilation.obj"
	@echo "... dcc_lib_autogen/mocs_compilation.i"
	@echo "... dcc_lib_autogen/mocs_compilation.s"
	@echo "... dcc_original_autogen/mocs_compilation.obj"
	@echo "... dcc_original_autogen/mocs_compilation.i"
	@echo "... dcc_original_autogen/mocs_compilation.s"
	@echo "... src/BasicBlock.obj"
	@echo "... src/BasicBlock.i"
	@echo "... src/BasicBlock.s"
	@echo "... src/CallConvention.obj"
	@echo "... src/CallConvention.i"
	@echo "... src/CallConvention.s"
	@echo "... src/DccFrontend.obj"
	@echo "... src/DccFrontend.i"
	@echo "... src/DccFrontend.s"
	@echo "... src/Procedure.obj"
	@echo "... src/Procedure.i"
	@echo "... src/Procedure.s"
	@echo "... src/RegisterNode.obj"
	@echo "... src/RegisterNode.i"
	@echo "... src/RegisterNode.s"
	@echo "... src/ast.obj"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/backend.obj"
	@echo "... src/backend.i"
	@echo "... src/backend.s"
	@echo "... src/bundle.obj"
	@echo "... src/bundle.i"
	@echo "... src/bundle.s"
	@echo "... src/chklib.obj"
	@echo "... src/chklib.i"
	@echo "... src/chklib.s"
	@echo "... src/comwrite.obj"
	@echo "... src/comwrite.i"
	@echo "... src/comwrite.s"
	@echo "... src/control.obj"
	@echo "... src/control.i"
	@echo "... src/control.s"
	@echo "... src/dataflow.obj"
	@echo "... src/dataflow.i"
	@echo "... src/dataflow.s"
	@echo "... src/dcc.obj"
	@echo "... src/dcc.i"
	@echo "... src/dcc.s"
	@echo "... src/dcc_interface.obj"
	@echo "... src/dcc_interface.i"
	@echo "... src/dcc_interface.s"
	@echo "... src/disassem.obj"
	@echo "... src/disassem.i"
	@echo "... src/disassem.s"
	@echo "... src/error.obj"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/fixwild.obj"
	@echo "... src/fixwild.i"
	@echo "... src/fixwild.s"
	@echo "... src/graph.obj"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/hlicode.obj"
	@echo "... src/hlicode.i"
	@echo "... src/hlicode.s"
	@echo "... src/hltype.obj"
	@echo "... src/hltype.i"
	@echo "... src/hltype.s"
	@echo "... src/icode.obj"
	@echo "... src/icode.i"
	@echo "... src/icode.s"
	@echo "... src/idioms.obj"
	@echo "... src/idioms.i"
	@echo "... src/idioms.s"
	@echo "... src/idioms/arith_idioms.obj"
	@echo "... src/idioms/arith_idioms.i"
	@echo "... src/idioms/arith_idioms.s"
	@echo "... src/idioms/call_idioms.obj"
	@echo "... src/idioms/call_idioms.i"
	@echo "... src/idioms/call_idioms.s"
	@echo "... src/idioms/epilogue_idioms.obj"
	@echo "... src/idioms/epilogue_idioms.i"
	@echo "... src/idioms/epilogue_idioms.s"
	@echo "... src/idioms/idiom1.obj"
	@echo "... src/idioms/idiom1.i"
	@echo "... src/idioms/idiom1.s"
	@echo "... src/idioms/mov_idioms.obj"
	@echo "... src/idioms/mov_idioms.i"
	@echo "... src/idioms/mov_idioms.s"
	@echo "... src/idioms/neg_idioms.obj"
	@echo "... src/idioms/neg_idioms.i"
	@echo "... src/idioms/neg_idioms.s"
	@echo "... src/idioms/shift_idioms.obj"
	@echo "... src/idioms/shift_idioms.i"
	@echo "... src/idioms/shift_idioms.s"
	@echo "... src/idioms/xor_idioms.obj"
	@echo "... src/idioms/xor_idioms.i"
	@echo "... src/idioms/xor_idioms.s"
	@echo "... src/liveness_set.obj"
	@echo "... src/liveness_set.i"
	@echo "... src/liveness_set.s"
	@echo "... src/locident.obj"
	@echo "... src/locident.i"
	@echo "... src/locident.s"
	@echo "... src/machine_x86.obj"
	@echo "... src/machine_x86.i"
	@echo "... src/machine_x86.s"
	@echo "... src/parser.obj"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/procs.obj"
	@echo "... src/procs.i"
	@echo "... src/procs.s"
	@echo "... src/project.obj"
	@echo "... src/project.i"
	@echo "... src/project.s"
	@echo "... src/proplong.obj"
	@echo "... src/proplong.i"
	@echo "... src/proplong.s"
	@echo "... src/reducible.obj"
	@echo "... src/reducible.i"
	@echo "... src/reducible.s"
	@echo "... src/scanner.obj"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
	@echo "... src/symtab.obj"
	@echo "... src/symtab.i"
	@echo "... src/symtab.s"
	@echo "... src/udm.obj"
	@echo "... src/udm.i"
	@echo "... src/udm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

